apiVersion: v1
kind: Service
metadata:
  name: proxy-loadbalancer
  namespace: proxy-space
spec:
  selector:
    app: proxy
  ports:
    - port: 25565
      targetPort: 25577
      nodePort: 30009
      protocol: TCP
      name: velocity
  type: LoadBalancer