apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app:
spec:
  replicas: 1
  template:
    metadata:
      name: redis
      labels:
        app:
    spec:
      containers:
        - name: redis
          image: redis:latest
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app:
